### ISSUE TITLE
Links to documentation are outdated

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoinj-addons#10]
The links on https://github.com/msgilligan/bitcoinj-addons/blob/master/doc/index.adoc are no longer valid:

- https://github.com/msgilligan/bitcoinj-addons/blob/master/doc/apidoc/index.html
- https://github.com/msgilligan/bitcoinj-addons/blob/master/doc/addons-user-guide.html

**Comment by msgilligan** [comment]
Fixed: 730fa9aa15e6be24bc6e4d5ad04d567bd9436e94

Note there are three links in this file with three different *use cases*. For each use case there are three different *scenarios*:

1. Rendered to static HTML by asciidoctor (applies to local `file:` URLs in `build/site` and when published to Github pages.)
1. Previewed in Chrome (or Firefox) with asciidoctor extension.
1. Viewed directly in the Github repository and rendered by Github's server-side Asciidoctor.

The three files are:

* README
This one should always link to the latest README on Github, so it is an absolute reference.

* JavaDoc
This content is generated, so we're using an absolute reference to the Github pages site, so it will work when viewed in the repository on Github. (I suppose it might be possible use a conditional and to have it use a relative link to the generated JavaDoc in the other cases, but this isn't strictly necessary and I don't know how to do it yet.)

* User's Guide
This uses a [relative link](https://github.com/msgilligan/bitcoinj-addons/commit/730fa9aa15e6be24bc6e4d5ad04d567bd9436e94#diff-36c2fc411934a54efe245964140a7788R14) (with a conditional `outfilesuffix` [setting](https://github.com/msgilligan/bitcoinj-addons/commit/730fa9aa15e6be24bc6e4d5ad04d567bd9436e94#diff-36c2fc411934a54efe245964140a7788R4)) that will switch between `.adoc` and `.html` as appropriate.

**Comment by msgilligan** [comment]
@dexX7 Wanted to make sure you saw the above comments and commit diff as it may teach you a useful AsciiDoctor trick or two.

**Comment by dexX7** [comment]
@msgilligan: actually I'm not sure, if I understand.

I installed the [asciidoctor-chrome-extension](https://github.com/asciidoctor/asciidoctor-chrome-extension) and this is currently the behavior I see:

- When browsing on [index.adoc](https://github.com/msgilligan/bitcoinj-addons/blob/730fa9aa15e6be24bc6e4d5ad04d567bd9436e94/doc/index.adoc), then GitHub renders the document as usual, and there is a link to the user's guide as `.adoc` file. Clicking on that link redirects to the GitHub rendered version.

- When browsing on [index.adoc (raw)](https://raw.githubusercontent.com/msgilligan/bitcoinj-addons/730fa9aa15e6be24bc6e4d5ad04d567bd9436e94/doc/index.adoc), then it looks like it's rendered by my browser, and there is still the link to the user's guide as `.adoc` file. However, clicking on that link also redirects to the raw version.

**Comment by msgilligan** [comment]
I typically use the Chrome Extension to preview AsciiDoctor files that I'm editing locally in a text editor. (Although the IntelliJ plugin-in is pretty nice, too.)
