### ISSUE TITLE
Improve README.md, instructions and first use

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoinj-addons#2]
I'm a bit nitpicking here, but a few quick notes about the readme.

1) The `/` in the build example seems twisted:
```diff
-    .\gradlew bootRun
+    ./gradlew bootRun
```

2) The requirements should be stated, in particular that JDK 8 is required. It could be noted that `JAVA_HOME` must point to the correct version, when using `./gradlew`. It might be noted that [a list of packages] is downloaded, which can be relevant for someone with a mobile data connection.

3) It would be great, if there were a few lines to what could be expected, when running `./gradlew bootRun`. Before doing so I was wondering, how to use the project (i.e. I missed a "first use" example, and actually assumed the project focuses on a BitcoinJ RPC server), and then I was surprised for a moment, when I saw the rather wild messages of STOMP, until I noticed they are actually network messages. It was more obvious after the first transactions were listed.

It should be stated that `bootRun` connects to the P2P network.

---

Other than that, this is *really* nice! :)

Edit: just found the other gems, like http://localhost:8080/listPeers (login: admin/admin).

**Comment by msgilligan** [comment]
I love your nitpicking @dexX7 -- it shows that you care!

**Comment by msgilligan** [comment]
Should be resolved in 71397fd8596d5d4959dcec7951ae82038967633e. Closing. Let me know if I missed anything. Thanks!
