### ISSUE TITLE
Spock tests for libconsensus

### ISSUE THREAD

**Issue by msgilligan** [msgilligan/bitcoinj-addons#5]
Once a JVM binding is available for [libconsensus](https://github.com/bitcoin/bitcoin/blob/0.10/src/script/bitcoinconsensus.h), Spock tests could be a very good way to test both the JVM binding and libconsensus itself.

There is not much documentation on libconsensus at this point, but it is mentioned int the [Bitcoin Core 0.10.0 Release Notes](https://bitcoin.org/en/release/v0.10.0)

See also:

* https://github.com/bitcoin/bitcoin/pull/5235 [Merged]
* https://github.com/bitcoin/bitcoin/issues/5311 [Docs and Examples]

*Note*: Now the non-Omni-related Spock test functionality has been moved to bitcoinj-addons from [OmniJ](https://github.com/OmniLayer/OmniJ) I'm opening this issue here and closing https://github.com/OmniLayer/OmniJ/issues/55

**Comment by dexX7** [comment]
Currently it's really just one function to verify, whether some script executes correctly:

- https://github.com/bitcoin/bitcoin/blob/master/src/script/bitcoinconsensus.h

**Comment by msgilligan** [comment]
No JVM bindings yet, according to Google and [doc/shared-libraries.md](https://github.com/bitcoin/bitcoin/blob/master/doc/shared-libraries.md). How hard do you think they would be to create?

**Comment by msgilligan** [comment]
In February I asked on the **bitcoinj** mailing list in a post titled [libconsensus JVM bindings](https://groups.google.com/d/topic/bitcoinj/NubSBOHAkVU/discussion) and the link to the Lighthouse project was taken down.

I did some work with JNI 10+ years ago, but from the comments it sounds like [JNA](https://github.com/java-native-access/jna) is a better way to go.

Do you have any interest in working on this @dexX7 ?

**Comment by dexX7** [comment]
@msgilligan: I'm only [a bit](http://i0.kym-cdn.com/photos/images/original/000/234/765/b7e.jpg) familiar with this, but I was curious and gave it a try! :)

 - https://github.com/dexX7/java-libbitcoinconsensus

The actual binding sits in [LibBitcoinConsensus.java](https://github.com/dexX7/java-libbitcoinconsensus/blob/master/src/main/java/co/bitwatch/libbitcoinconsensus/LibBitcoinConsensus.java) and I started with a more convenient wrapper in [BitcoinConsensus.java](https://github.com/dexX7/java-libbitcoinconsensus/blob/master/src/main/java/co/bitwatch/libbitcoinconsensus/BitcoinConsensus.java).

[Rudamentary JUnit tests](https://github.com/dexX7/java-libbitcoinconsensus/tree/master/src/test/java/co/bitwatch/libbitcoinconsensus) are available.

**Comment by msgilligan** [comment]
Nice, @dexX7 ! Can't wait to try it out.

**Comment by msgilligan** [comment]
Would you accept a pull request with some Spock tests?

**Comment by dexX7** [comment]
Sure! I also added you as collaborator, just in case. I think there are a few interesting paths from here: it could become a plain wrapper, or combined with bitcoinj (I'm mostly thinking about the script/transaction representing classes), and I don't have specific plans.

**Comment by msgilligan** [comment]
Well, it seems the logical place for the Spock Tests would be in your new project, so I'm going to close this issue and forward it to https://github.com/dexX7/java-libbitcoinconsensus/issues/1.

**Comment by msgilligan** [comment]
I did a checkout, build and test on Mac OS X Yosemite. The tests all passed!

One little nit is that the Gradle build didn't seem to notice if I move or change (`touch`) the `libbitcoinconsensus.dylib` file. I also discovered that it works if the dylib is in project root or in `src/main/resources`
