### ISSUE TITLE
Make better use of Jackson

### ISSUE THREAD

**Issue by msgilligan** [msgilligan/bitcoinj-addons#9]
Better use of Jackson will help us to:

1. Eliminate repetitive conversion code from many methods
1. Replace remaining Maps with strongly-typed POJOs.

**Comment by msgilligan** [comment]
Progress report

1. Create POJOs for JsonRpcRequest and JsonRpcResponse: 0523aeb58c14e9ba578ed1060af7bff40ce987bb
2. Start customizing the ObjectMapper with a CoinDeserializer: 91f7cc1d67ad92956865ca9e543b76f01f839cab

What do you think, @dexX7 ?

**Comment by msgilligan** [comment]
TODO:

1. Split current `bitcoinj-json` project into two modules: `-json` (jackson stuff) and `-server` (services)
1. Make `bitcoinj-rpcclient` depend on `bitcoinj-json`
1. Move serializers and deserializers from `-rpcclient` into a Jackson module in `bitcoinj-json`.

**Comment by dexX7** [comment]
These changes are fantastic, really a great improvement!

In Omni Core we currently have a few results where some fields are omitted, depending on the state, e.g.  whether a crowdsale is closed, or active, whether a transaction is confirmed or unconfirmed, which makes mapping to plain data objects probably pretty difficult. Makes me wonder..

**Comment by msgilligan** [comment]
POJOs to create:

1. Block object - getBlock
1. Array/List of block hashes - setGenerate
1. "Raw" transaction as a map - signRawTransaction. getRawTransactionMap
1. List of ?? - listReceivedByAddress
1. List of UTXO - getTxOut
1. ?? - getTransaction (what should this return?)
1. Information object - getInfo
1. ?? - getChainTips

**Comment by msgilligan** [comment]
>  some fields are omitted, depending on the state ... which makes mapping to plain data objects probably pretty difficult.

Can't those fields just be nullable in the POJO?

**Comment by dexX7** [comment]
> List of UTXO - getTxOut

It returns a single unspent output or null, if the output is spent.

> Can't those fields just be nullable in the POJO?

Ah, sure.

**Comment by msgilligan** [comment]
>> List of UTXO - getTxOut
>
>It returns a single unspent output or null, if the output is spent.

Thanks. Fixed, above.

**Comment by msgilligan** [comment]
@dexX7 Finished all but (8) and (9) in the *POJOs to create* list. Any ideas or suggestions on (8) or (9)?

**Comment by dexX7** [comment]
If `getTransaction` refers to `gettransaction`, then this is a call to get a wallet transaction, which has some wallet specific information (such as listing potential conflicts, or the time of creation). If `getRawTransactionMap` refers to `getrawtransaction`, then it might either be mapped to a BitcoinJ transaction, or a new type: the verbose version has information about the chain (`blocktime`, `blockhash`, `confirmations` (stateful)).

**Comment by msgilligan** [comment]
Yes. In addition to mapping to `org.bitcoinj.core.Transaction` we're going to need to create POJOs for both `gettransaction` and `getrawtransaction`. They're required for making the server version and, as you point out, they contain info that is not available in bitcoinj's `Transaction`.

**Comment by msgilligan** [comment]
Finished in v0.0.10:  ff680a00f946af20f60a6ff52851609ee1f60671.
